In [10]:
import pandas as pd
import numpy as np

import pandas as pd

# Paths
vari_super_s1 = 'Measurements/vari_super_s1.csv'
vari_super_s2 = 'Measurements/vari_super_s2.csv'
vari_precog_s1 = 'Measurements/vari_precog_s1.csv'
vari_precog_s2 = 'Measurements/vari_precog_s2.csv'
vari_precog_s3 = 'Measurements/vari_precog_s3.csv'
vari_nymz = 'Measurements/vari_nymz.csv'
vari_hobbytalk_stock = 'Measurements/vari_hobbytalk_stock.csv'
vari_hbb = 'Measurements/vari_hbb.csv'
vari_harpo = 'Measurements/vari_harpo.csv'
vari_gizaudio = 'Measurements/vari_gizaudio.csv'
vari_crinacle = 'Measurements/vari_crinacle.csv'
vari_aftersound = 'Measurements/vari_aftersound.csv'
CammyFi = 'Measurements/CammyFi.csv'
BryAudioReviews = 'Measurements/BryAudioReviews.csv'
Vari_105dBC = 'Measurements/Vari_105dBC.csv'
Vari_85dBC = 'Measurements/Vari_85dBC.csv'
Vari_77dBC = 'Measurements/Vari_77dBC.csv'
Moondrop_Measurement_Official = 'Measurements/Moondrop_Measurement_Official.csv'

# A list of all the paths to the csv files
file_list = [vari_super_s1, vari_super_s2, vari_precog_s1, vari_precog_s2, vari_precog_s3, vari_nymz, vari_hobbytalk_stock, vari_hbb, vari_harpo, vari_gizaudio, vari_crinacle, vari_aftersound, CammyFi, BryAudioReviews]

# Step 2
df_list = []
for file_name in file_list:
    df = pd.read_csv(file_name)
    df_list.append(df)

# Step 3
concatenated_df = pd.concat(df_list)

# Step 4
grouped_df = concatenated_df.groupby('X').mean()

# Step 5
grouped_df.to_csv('averaged_data.csv')

grouped_df

                      Y
X
19.927637     68.047066
20.071734     70.460251
20.097790     69.042553
20.162717     69.518828
20.169072     70.441110
...                 ...
19693.234796  43.976038
19794.639685  52.573222
19794.801701  49.622421
19794.963463  36.987448
19897.054900  51.596054

[10536 rows x 1 columns]